<a href="https://colab.research.google.com/github/incrisvel/adaptaste/blob/main/similarity_clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%pip -q install pandas scikit-learn plotly

In [3]:
import pandas as pd
import json

# Abre arquivo de reviews
with open('reviews_preprocessed.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

preprocessed_reviews_df = pd.DataFrame(data)

In [4]:
preprocessed_reviews_df.head()

,review_id,created_date,place_id,review_text,description_clean,description_tokenized,description_normalized,description_no_stopwords,description_stemmed,description_lemmatized,description_bigrams
0,ChZDSUhNMG9nS0VJQ0FnSURqNXZHSUZ3EAE,2026-08-29T14:58:24.831679+00:00,0x94df1975c038b80f:0,Le lieu est très beau et renové avec beaucoup ...,Le lieu est très beau et renové avec beaucoup ...,"[Le, lieu, est, très, beau, et, renové, avec, ...","[le, lieu, est, très, beau, et, renové, avec, ...","[le, lieu, est, très, beau, et, renové, avec, ...","[le, lieu, est, trè, beau, et, renové, avec, b...","[Le, lieu, est, très, beau, et, renovér, avec,...","[[Le, lieu], [lieu, est], [est, très], [très, ..."
1,Ci9DQUlRQUNvZENodHljRjlvT21GeGNISlZWbk5KVkVvdE...,2026-08-29T14:58:24.211967+00:00,0x94df1975c038b80f:0,Café da tarde,Café da tarde,"[Café, da, tarde]","[café, da, tarde]","[café, tarde]","[café, tard]","[café, tarde]","[[café, tarde]]"
2,Ci9DQUlRQUNvZENodHljRjlvT21ORFV6UXRkWGhIWmpBM1...,2026-08-29T14:58:23.738514+00:00,0x94df1975c038b80f:0,Melhor restaurante de Blumenau com 2 opções ce...,Melhor restaurante de Blumenau com 2 opções ce...,"[Melhor, restaurante, de, Blumenau, com, 2, op...","[melhor, restaurante, de, blumenau, com, opçõe...","[melhor, restaurante, blumenau, opções, centro...","[melhor, restaurant, blumenau, opç, centr, bairr]","[bom, restaurante, blumenau, opção, Centro, Ba...","[[bom, restaurante], [restaurante, blumenau], ..."
3,Ci9DQUlRQUNvZENodHljRjlvT21aQk9ERnpVVTlCU25KTG...,2026-08-29T14:58:23.242554+00:00,0x94df1975c038b80f:0,"Ambiente muito agradável, comida de qualidade ...","Ambiente muito agradável, comida de qualidade ...","[Ambiente, muito, agradável, ,, comida, de, qu...","[ambiente, muito, agradável, comida, de, quali...","[ambiente, muito, agradável, comida, qualidade...","[ambi, muit, agrad, com, qual, atend, excel, e...","[ambiente, muito, agradável, comer, qualidade,...","[[ambiente, muito], [muito, agradável], [agrad..."
4,ChdDSUhNMG9nS0VJQ0FnSURQalllTml3RRAB,2026-08-29T14:58:17.436936+00:00,0x94df1975c038b80f:0,Local fantástico.,Local fantástico.,"[Local, fantástico, .]","[local, fantástico]","[local, fantástico]","[local, fant]","[local, fantástico]","[[local, fantástico]]"

# Bag of Words

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

# Extrai todos os tokens de todas as reviews
tokens_column = preprocessed_reviews_df["description_no_stopwords"]
tokens = tokens_column.tolist()

bow_vectorizer = CountVectorizer(
    analyzer=lambda tokens: tokens
)
bow_matrix = bow_vectorizer.fit_transform(
    tokens_column
)

# Recupera o vocabulário
bow_words = bow_vectorizer.get_feature_names_out()

# Transforma a matriz em DataFrame
df_bow = pd.DataFrame(
    bow_matrix.toarray(),
    columns=bow_words
)

# Adicionar o ID para conectar com a base original
df_bow.insert(0, "review_text", preprocessed_reviews_df["review_text"].values)

# Visualizar
df_bow.head()

,review_text,aa,aaaaaameiiii,aaaaamei,aah,abacate,abacaxi,abafado,abaixar,abaixarem,...,últimos,única,únicas,único,únicos,úteis,útil,über,überfordert,ė
0,Le lieu est très beau et renové avec beaucoup ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Café da tarde,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Melhor restaurante de Blumenau com 2 opções ce...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"Ambiente muito agradável, comida de qualidade ...",0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,Local fantástico.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# TF-IDF

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Criar o modelo TF-IDF
tfidf_vectorizer = TfidfVectorizer(
    analyzer=lambda tokens: tokens
)

# Criar matriz
tfidf_matrix = tfidf_vectorizer.fit_transform(
    preprocessed_reviews_df["description_no_stopwords"]
)

# Recuperar o vocabulário
tfidf_words = tfidf_vectorizer.get_feature_names_out()

# Transformar matriz em DF
df_tfidf = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_words
)

df_tfidf.insert(0, "review_text", preprocessed_reviews_df["review_text"].values)

df_tfidf.head(20)

,review_text,aa,aaaaaameiiii,aaaaamei,aah,abacate,abacaxi,abafado,abaixar,abaixarem,...,últimos,única,únicas,único,únicos,úteis,útil,über,überfordert,ė
0,Le lieu est très beau et renové avec beaucoup ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,Café da tarde,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,Melhor restaurante de Blumenau com 2 opções ce...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,"Ambiente muito agradável, comida de qualidade ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.169568,0.0,0.0,0.0,0.0,0.0,0.0
4,Local fantástico.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
5,Uma experiência deliciosa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
6,Muito bom!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
7,Comida saudável,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
8,Experiência incrível,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
9,Ótimo em tudo !,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
10,"Sofisticado, aconchegante",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
11,Amo o Âme!💖,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
12,"São ótimos, recomendo!",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
13,Gostei bastante!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
14,Excelente atendimento e comida sensacional!!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
15,Ambiente com uma energia incrível!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
16,"Lugar lindo, comida gostosa, recomendo",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
17,Lugar muito agradável e comida deliciosa!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
18,Delícia de lugar.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
19,Belo local mas a comida estava fria!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

# Similaridade entre textos

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
# Calcula similaridade a partir do BoW
similarity_bow = cosine_similarity(
    df_bow.drop(columns="review_text")
)

dt_sim_bow = pd.DataFrame(
    similarity_bow,
    index=preprocessed_reviews_df["review_text"],
    columns=preprocessed_reviews_df["review_text"]
)

dt_sim_bow.head()

review_text,"Le lieu est très beau et renové avec beaucoup de charme.\nla nourriture est variée et de qualité, je recommande !",Café da tarde,Melhor restaurante de Blumenau com 2 opções centro e bairro,"Ambiente muito agradável, comida de qualidade e atendimento excelente, com uma equipe sempre educada e bem preparada. O único ponto que acredito que poderia ser revisto é o formato do almoço: seria interessante oferecer a opção por quilo e também um valor fixo para o buffet livre, pois o preço final por quilo acaba ficando bastante alto. No geral, é um lugar que gosto e recomendo.",Local fantástico.,Uma experiência deliciosa,Muito bom!,Comida saudável,Experiência incrível,Ótimo em tudo !,...,"O local possui um cardápio variado, com sugestões dos mais pedidos da casa e fotos de alguns dos pratos o que facilita na hora da escolha. As bebidas e os pratos principais chegaram muito rápido. Apresentação 10/10 e sabor 10/1000. Atendimento excelente do Wil. Voltaremos mais vezes!!","Ambiente agradável limpo e bonito, ótimo atendimento dos funcionários, principalmente do Will que me recebeu.\nPedi uma lasanha bolonhesa, não estava gostosa.\nPróxima vez vou tentar a pizza!","Pizza maravilhosa. Massa muito saborosa e o molho de tomate muito gostoso. O atendimento também foi muito bom, fomos atendidos pelo Will.\nO ambiente é muito agradável!\nQuero voltar mais vezes!","Que delícia de experiência! Comida super saborosa e atendimento ótimo, em especial o Will. Fomos bem recebidos e com certeza voltaremos.","Tudo excelente. Comida boa, ambiente legal, atendimento rápido e eficaz. Recomendo a todos que estiverem passando pela região. Cardápio com variedade muito boa também.","Fomos almoçar as 13:30h, o buffet claro ja estava desfalcado, mas o preço é bom, pra quem quer comida básica, não espere carnes nobres ou ao alho e óleo, mas acredito que se a vigilância sanitária passar ali terão muitas correções a fazer, enfim... o barato sai caro.","Comida caseira, bem feita. Lugar tranquilo, limpo, organizado.","Sou frequentador assiduo. Super recomendo. Um ambiente muito bom, comida super caseira e o serviço é nota 10.","Restaurante incrível para dia de semana, ambiente simples porém impecável na limpeza, comida com buffet muito bem elaborado com tempero caseiro delicioso, além de um capricho especial, sempre tem alguém cuidando do buffet. Os funcionários são super bem treinados, atenciosos e educados. Meu restaurante preferido para almoços de dia de semana.","Muito bom! Me surpreendi bastante com a qualidade e quantidade de opções, comida caseira e super saborosa\nO risoto e nhoque mesmo estavam divinos!"
review_text,,,,,,,,,,,,,,,,,,,,,
"Le lieu est très beau et renové avec beaucoup de charme.\nla nourriture est variée et de qualité, je recommande !",0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Café da tarde,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Melhor restaurante de Blumenau com 2 opções centro e bairro,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Ambiente muito agradável, comida de qualidade e atendimento excelente, com uma equipe sempre educada e bem preparada. O único ponto que acredito que poderia ser revisto é o formato do almoço: seria interessante oferecer a opção por quilo e também um valor fixo para o buffet livre, pois o preço final por quilo acaba ficando bastante alto. No geral, é um lugar que gosto e recomendo.",0.0,0.0,0.0,0.02439,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Local fantástico.,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Calcula similaridade a partir do TF-IDF
similarity_tfidf = cosine_similarity(
    df_tfidf.drop(columns="review_text")
)

dt_sim_tfidf = pd.DataFrame(
    similarity_tfidf,
    index=preprocessed_reviews_df["review_text"],
    columns=preprocessed_reviews_df["review_text"]
)

dt_sim_tfidf.head()

# Heatmap de similaridade

In [ ]:
import plotly.graph_objects as go

texts = preprocessed_reviews_df["review_text"]

def create_heatmap(matrix, title):
  custom_data = []

  for i in range(len(texts)):
    line = []

    for j in range(len(texts)):
      line.append([
          texts[i],
          texts[j]
      ])

    custom_data.append(line)

  fig = go.Figure(
      data=go.Heatmap(
          z=matrix,
          x=texts,
          y=texts,
          colorscale="Pinks",
          zmin=0,
          zmax=1,
          customdata=custom_data,
          hovertemplate=
            "<b>%{customdata[0]}</b><br>"
                "<b>%{customdata[1]}</b><br>"
                "<b>Similaridade:</b> %{z:.3f}"
                "<extra></extra>"
      )
  )

  fig.update_layout(
      title=title,
      xaxis_title="Review",
      yaxis_title="Review",
      width=900,
      height=850
  )

  fig.show()

In [ ]:
create_heatmap(
    similarity_bow,
    "Similaridade entre reviews — Bag of Words"
)

In [ ]:
create_heatmap(
    similarity_tfidf,
    "Similaridade entre reviews — TF-IDF"
)